### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by jhrozek** [jhrozek/pam_wrapper#1]
Currently we don't work on Ubuntu. Need to fix this.

**Comment by cryptomilk** [comment]
What fails?

**Comment by jhrozek** [comment]
Looks like Debian uses a different multilib path schema for shared 
libraries than Fedora or Suse, but I haven't looked closer:

  Test command: /home/vagrant/pam_wrapper/obj/tests/test_pam_wrapper
  Test timeout computed to be: 1500
  PWRAP_ERROR(1116): Failed to read libpam.so link

And these are the libraries:
/lib/x86_64-linux-gnu/libpam.so.0
/lib/x86_64-linux-gnu/libpam.so.0.83.0
/lib/x86_64-linux-gnu/libpam_misc.so.0
/lib/x86_64-linux-gnu/libpam_misc.so.0.82.0
/lib/x86_64-linux-gnu/libpamc.so.0
/lib/x86_64-linux-gnu/libpamc.so.0.82.1
/usr/lib/x86_64-linux-gnu/libpam.a
/usr/lib/x86_64-linux-gnu/libpam.so
/usr/lib/x86_64-linux-gnu/libpam_misc.a
/usr/lib/x86_64-linux-gnu/libpam_misc.so
/usr/lib/x86_64-linux-gnu/libpamc.a
/usr/lib/x86_64-linux-gnu/libpamc.so

So maybe we need a configure-time option to specify the libdir.

**Comment by cryptomilk** [comment]
We could use 'find_library' to look for libpam.so in cmake and then store the location in config.h ...

**Comment by jhrozek** [comment]
Done: https://github.com/jhrozek/pam_wrapper/commit/4ddc605a29e64bb584d695ea95f99d3821388814
