### ISSUE TITLE
Move pwrap_pam to the Matrix

### ISSUE THREAD

**Issue by jhrozek** [jhrozek/pam_wrapper#5]
11:05 <gladiac> rv = pam_start("pwrap_pam", "testuser", -> pam_start("matrix", "trinity", ...
11:05 <jhrozek> :-) 
11:05 <gladiac> could you change it? :)
11:05 <gladiac> testuser2 -> neo

**Comment by cryptomilk** [comment]
Like!

**Comment by jhrozek** [comment]
done in master
